// Code generated by MockGen. DO NOT EDIT.
// Source: obsidian/sync.go
//
// Generated by this command:
//
//	mockgen -source=obsidian/sync.go -package=obsidian -destination=obsidian/mock_conn_test.go -mock_names=wsConn=MockWSConn
//

// Package obsidian is a generated GoMock package.
package obsidian

import (
	context "context"
	reflect "reflect"

	websocket "github.com/coder/websocket"
	gomock "go.uber.org/mock/gomock"
)

// MockWSConn is a mock of wsConn interface.
type MockWSConn struct {
	ctrl     *gomock.Controller
	recorder *MockWSConnMockRecorder
	isgomock struct{}
}

// MockWSConnMockRecorder is the mock recorder for MockWSConn.
type MockWSConnMockRecorder struct {
	mock *MockWSConn
}

// NewMockWSConn creates a new mock instance.
func NewMockWSConn(ctrl *gomock.Controller) *MockWSConn {
	mock := &MockWSConn{ctrl: ctrl}
	mock.recorder = &MockWSConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWSConn) EXPECT() *MockWSConnMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockWSConn) Close(code websocket.StatusCode, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", code, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockWSConnMockRecorder) Close(code, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWSConn)(nil).Close), code, reason)
}

// Read mocks base method.
func (m *MockWSConn) Read(ctx context.Context) (websocket.MessageType, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", ctx)
	ret0, _ := ret[0].(websocket.MessageType)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Read indicates an expected call of Read.
func (mr *MockWSConnMockRecorder) Read(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockWSConn)(nil).Read), ctx)
}

// SetReadLimit mocks base method.
func (m *MockWSConn) SetReadLimit(n int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetReadLimit", n)
}

// SetReadLimit indicates an expected call of SetReadLimit.
func (mr *MockWSConnMockRecorder) SetReadLimit(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReadLimit", reflect.TypeOf((*MockWSConn)(nil).SetReadLimit), n)
}

// Write mocks base method.
func (m *MockWSConn) Write(ctx context.Context, typ websocket.MessageType, p []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", ctx, typ, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockWSConnMockRecorder) Write(ctx, typ, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockWSConn)(nil).Write), ctx, typ, p)
}
