// Code generated by MockGen. DO NOT EDIT.
// Source: obsidian/watcher.go
//
// Generated by this command:
//
//	mockgen -source=obsidian/watcher.go -package=obsidian -destination=obsidian/mock_pusher_test.go -mock_names=syncPusher=MockSyncPusher
//

// Package obsidian is a generated GoMock package.
package obsidian

import (
	context "context"
	reflect "reflect"

	state "github.com/alexjbarnes/vault-sync/internal/state"
	gomock "go.uber.org/mock/gomock"
)

// MockSyncPusher is a mock of syncPusher interface.
type MockSyncPusher struct {
	ctrl     *gomock.Controller
	recorder *MockSyncPusherMockRecorder
	isgomock struct{}
}

// MockSyncPusherMockRecorder is the mock recorder for MockSyncPusher.
type MockSyncPusherMockRecorder struct {
	mock *MockSyncPusher
}

// NewMockSyncPusher creates a new mock instance.
func NewMockSyncPusher(ctrl *gomock.Controller) *MockSyncPusher {
	mock := &MockSyncPusher{ctrl: ctrl}
	mock.recorder = &MockSyncPusherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncPusher) EXPECT() *MockSyncPusherMockRecorder {
	return m.recorder
}

// Connected mocks base method.
func (m *MockSyncPusher) Connected() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connected")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Connected indicates an expected call of Connected.
func (mr *MockSyncPusherMockRecorder) Connected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connected", reflect.TypeOf((*MockSyncPusher)(nil).Connected))
}

// ContentHash mocks base method.
func (m *MockSyncPusher) ContentHash(relPath string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContentHash", relPath)
	ret0, _ := ret[0].(string)
	return ret0
}

// ContentHash indicates an expected call of ContentHash.
func (mr *MockSyncPusherMockRecorder) ContentHash(relPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContentHash", reflect.TypeOf((*MockSyncPusher)(nil).ContentHash), relPath)
}

// Push mocks base method.
func (m *MockSyncPusher) Push(ctx context.Context, path string, content []byte, mtime, ctime int64, isFolder, isDeleted bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push", ctx, path, content, mtime, ctime, isFolder, isDeleted)
	ret0, _ := ret[0].(error)
	return ret0
}

// Push indicates an expected call of Push.
func (mr *MockSyncPusherMockRecorder) Push(ctx, path, content, mtime, ctime, isFolder, isDeleted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockSyncPusher)(nil).Push), ctx, path, content, mtime, ctime, isFolder, isDeleted)
}

// ServerFileState mocks base method.
func (m *MockSyncPusher) ServerFileState(path string) *state.ServerFile {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServerFileState", path)
	ret0, _ := ret[0].(*state.ServerFile)
	return ret0
}

// ServerFileState indicates an expected call of ServerFileState.
func (mr *MockSyncPusherMockRecorder) ServerFileState(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServerFileState", reflect.TypeOf((*MockSyncPusher)(nil).ServerFileState), path)
}
